import type { Invoice } from '@/types/invoice';

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 'RT3080',
    createdAt: '2021-08-15',
    paymentDue: '2021-08-19',
    description: 'Graphic Design',
    paymentTerms: 4,
    clientName: 'Jensen Huang',
    clientEmail: 'jensen@nvidia.com',
    status: 'paid',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '106 Kendell Street', city: 'Gifford', postCode: 'G51 3UD', country: 'United Kingdom' },
    items: [{ id: '1', name: 'Brand Guidelines', quantity: 1, price: 1800.90, total: 1800.90 }],
    total: 1800.90,
  },
  {
    id: 'XM9141',
    createdAt: '2021-08-21',
    paymentDue: '2021-09-20',
    description: 'Graphic Design',
    paymentTerms: 30,
    clientName: 'Alex Grim',
    clientEmail: 'alexgrim@mail.com',
    status: 'pending',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '84 Church Way', city: 'Bradford', postCode: 'BD1 9PB', country: 'United Kingdom' },
    items: [
      { id: '1', name: 'Banner Design', quantity: 1, price: 156.00, total: 156.00 },
      { id: '2', name: 'Email Design', quantity: 2, price: 200.00, total: 400.00 }
    ],
    total: 556.00,
  },
  {
    id: 'RG0314',
    createdAt: '2021-10-01',
    paymentDue: '2021-10-01',
    description: 'E-Commerce Platform',
    paymentTerms: 30,
    clientName: 'John Morrison',
    clientEmail: 'john@morrison.com',
    status: 'paid',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '79 Dover Street', city: 'Wigan', postCode: 'WN1 1AG', country: 'United Kingdom' },
    items: [{ id: '1', name: 'Platform Setup', quantity: 1, price: 14002.33, total: 14002.33 }],
    total: 14002.33,
  },
  {
    id: 'RT2080',
    createdAt: '2021-10-12',
    paymentDue: '2021-10-12',
    description: 'Logo Design',
    paymentTerms: 30,
    clientName: 'Alysa Werner',
    clientEmail: 'alysa@werner.com',
    status: 'pending',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '46 Surrey Row', city: 'Durham', postCode: 'DH1 3DA', country: 'United Kingdom' },
    items: [{ id: '1', name: 'Identity Design', quantity: 1, price: 102.04, total: 102.04 }],
    total: 102.04,
  },
  {
    id: 'AA1449',
    createdAt: '2021-10-14',
    paymentDue: '2021-10-14',
    description: 'Cloud Migration',
    paymentTerms: 30,
    clientName: 'Mellisa Clarke',
    clientEmail: 'mellisa@clarke.com',
    status: 'pending',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '34 Seymour Lane', city: 'Sheffield', postCode: 'S9 5BA', country: 'United Kingdom' },
    items: [{ id: '1', name: 'Infrastructure Migration', quantity: 1, price: 4032.33, total: 4032.33 }],
    total: 4032.33,
  },
  {
    id: 'TY9141',
    createdAt: '2021-10-31',
    paymentDue: '2021-10-31',
    description: 'API Development',
    paymentTerms: 30,
    clientName: 'Thomas Wayne',
    clientEmail: 'thomas@wayne.com',
    status: 'pending',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '63 William Street', city: 'Newcastle', postCode: 'NE1 1TF', country: 'United Kingdom' },
    items: [{ id: '1', name: 'REST API', quantity: 1, price: 6155.91, total: 6155.91 }],
    total: 6155.91,
  },
  {
    id: 'FV2353',
    createdAt: '2021-11-12',
    paymentDue: '2021-11-12',
    description: 'App Design',
    paymentTerms: 30,
    clientName: 'Anita Wainwright',
    clientEmail: 'anita@wainwright.com',
    status: 'draft',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '22 Crossfield Road', city: 'Manchester', postCode: 'M35 0DA', country: 'United Kingdom' },
    items: [{ id: '1', name: 'UI/UX Design', quantity: 1, price: 3102.04, total: 3102.04 }],
    total: 3102.04,
  },
  {
    id: 'BC8765',
    createdAt: '2022-01-05',
    paymentDue: '2022-01-12',
    description: 'Website Redesign',
    paymentTerms: 7,
    clientName: 'Laura Palmer',
    clientEmail: 'laura@palmer.com',
    status: 'paid',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '123 Twin Peaks', city: 'Washington', postCode: '98045', country: 'United States' },
    items: [{ id: '1', name: 'Full Redesign', quantity: 1, price: 10000.00, total: 10000.00 }],
    total: 10000.00,
  },
  {
    id: 'DE9012',
    createdAt: '2022-02-15',
    paymentDue: '2022-03-17',
    description: 'Mobile App Development',
    paymentTerms: 30,
    clientName: 'Dale Cooper',
    clientEmail: 'dale@fbi.gov',
    status: 'pending',
    senderAddress: { street: '19 Union Terrace', city: 'London', postCode: 'E1 3EZ', country: 'United Kingdom' },
    clientAddress: { street: '987 Great Northern', city: 'Washington', postCode: '98045', country: 'United States' },
    items: [
      { id: '1', name: 'iOS App', quantity: 1, price: 25000.00, total: 25000.00 },
      { id: '2', name: 'Android App', quantity: 1, price: 25000.00, total: 25000.00 }
    ],
    total: 50000.00,
  },
];
